version: "3.9"
services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
  ping:
    build:
      context: .
      dockerfile: Dockerfile-ping
    links:
      - web
